spring:
  jpa:
    properties:
      hibernate:
          hbm2ddl.auto: validate
          show_sql: false
          format_sql: false
          use_sql_comments: false
liquibase:
  change-log: classpath:/db/changelog/master.xml
  
---

spring:
  profiles: mysql
  jpa:
    properties:
      hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect                   
  datasource:
    url: jdbc:mysql://localhost/sbmm
    username: sbmm
    password: sbmm
  
---

spring:
  profiles: embeddeddb
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:sbmm